version: '3.8'

services:
  # ========================================
  # Inventory Management Service
  # ========================================
  inventory-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-service
    
    ports:
      - "8081:8081"  # API REST
    
    environment:
      # Spring Boot
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_PORT=8081
      
      # Database H2 (in-memory)
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:inventory
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      
      # Logs
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_COM_INVENTORY=DEBUG
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    networks:
      - inventory-network

# ========================================
# Networks
# ========================================
networks:
  inventory-network:
    driver: bridge
    name: inventory-network